### ISSUE TITLE
[Error] 

### ISSUE THREAD

**Issue by NexDK** [vipexv/v-vehControl#3]
Sometimes you get a bunch of errors.

CrBrowserMain/ Uncaught (in promise) TypeError: Failed to fetch (@v-vehcontrol/web/dist/assets/index-qrl3sgWi.js:43)

**Comment by vipexv** [comment]
Sorry for the late reply, but it doesn't actually affect anything, most likely due to me not returning anything on the callback, i'll look into it soon.

**Comment by NexDK** [comment]
Sound great, thanks :-)

**Comment by vipexv** [comment]
I'll see if this is fixed in 1.0.7

**Comment by NexDK** [comment]
Great thanks 👍

**Comment by NexDK** [comment]
Hi, i just tested it after the update now the error is gone 👍 

Is it normal the menu moves when you are opening the trunk and hood ? here is a video there shows it https://youtu.be/WOOF_90Pe2E

**Comment by vipexv** [comment]
It shouldn't be that way, the size seems to change due to the new icon, i'll fix it in the future.

**Comment by NexDK** [comment]
Great thanks 👍

**Comment by vipexv** [comment]
This is fixed in the new update, please download the latest release.
